name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Change if using another branch
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Ensure themes are cloned
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Site
        run: hugo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT_WEBSITE }}
          publish_dir: ./public  # Ensure this matches your output folder
          target_branch: gh-pages  # This is where it will push the site
